FROM play_image:1.0

RUN apt-get update \
    && apt-get install \
    curl \
    kmod \
    fuse libfuse2 \
        --assume-yes --no-install-recommends && apt-get clean && rm -rf /var/lib/apt/lists/*

RUN modprobe fuse \
&& groupadd fuse \
&& user="$(whoami)" \
&& usermod -a -G fuse $user

RUN CUSTOM_NVIM_PATH=/usr/local/bin/nvim.appimage \
	&& curl -o ${CUSTOM_NVIM_PATH} -LO https://github.com/neovim/neovim/releases/latest/download/nvim.appimage \
	&& chmod a+x ${CUSTOM_NVIM_PATH} \
	&& set -u \
	&& update-alternatives --install /usr/bin/nvim nvim "${CUSTOM_NVIM_PATH}" 110

RUN update-alternatives --install /usr/bin/vi vi /usr/bin/nvim 1 && \
 update-alternatives --set vi /usr/bin/nvim

