FROM play_image:1.0

# Set image locale.
ENV LANG en_US.UTF-8
ENV LANGUAGE en_US:en
ENV TZ=Europe/London

RUN apt-get update \
    && DEBIAN_FRONTEND=noninteractive apt-get install \
    curl kmod \
    fzf ripgrep tree xclip zip unzip \
    gettext \
        --assume-yes --no-install-recommends && apt-get clean && rm -rf /var/lib/apt/lists/*

# Install Neovim from source.
RUN mkdir -p /root/TMP \
&& cd /root/TMP && git clone https://github.com/neovim/neovim \
&& cd /root/TMP/neovim && git checkout stable && make -j4 && make install \
&& rm -rf /root/TMP

RUN update-alternatives --install /usr/local/bin/vi vi /usr/local/bin/nvim 1 && \
  update-alternatives --set vi /usr/local/bin/nvim

# Pynvim
RUN pip3 install pynvim

# Deno
ENV DENO_INSTALL="/usr/local"
RUN curl -fsSL https://deno.land/x/install/install.sh | sh

# Map rg to ag
RUN update-alternatives --install /usr/local/bin/ag ag /usr/bin/rg 1

# Notebook
RUN pip3 install notebook pudb

# Install robot descriptions  
RUN pip3 install robot_descriptions
ENV ROBOT_DESCRIPTIONS_CACHE=/workdir/

# Configurations
RUN apt-get update \
    && DEBIAN_FRONTEND=noninteractive apt-get install \
    tmux zsh tig \
        --assume-yes --no-install-recommends && apt-get clean && rm -rf /var/lib/apt/lists/*
	
RUN sh -c "$(curl -fsSL https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"

# Configure tmux
RUN mkdir -p /root/TMP \
&& cd /root/TMP && git clone https://github.com/andrei-herdt/dotfiles \
&& cp /root/TMP/dotfiles/.tmux.conf ~ \
&& rm -rf /root/TMP

# Configure git
RUN git config --global --add safe.directory /workdir/playground \
&& git config --global user.email "andrei.herdt@gmail.com" \
&& git config --global user.name "Andrei Herdt" \
&& git config --global core.editor vi
